# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Data Story Project
author: Your Team Number

# Disable execution of notebooks during build
execute:
  execute_notebooks: "off"

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/EfeKarataz/IVGroup7
  path_to_book: docs
  branch: main

html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

sphinx:
  extra_extensions:
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
